dist: xenial
language: python
jobs:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
install:
- python3 -m pip install pydiatra pyflakes
script:
- python3 -m pydiatra github-*
- python3 -m pyflakes github-*

# vim:ts=2 sts=2 sw=2 et
