name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-18.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v github-*
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes github-*
    - name: smoke test
      run: |
        ./github-editmeta --help
        ./github-editmeta ${{github.repository}}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        EDITOR: cat

# vim:ts=2 sts=2 sw=2 et
